### ISSUE TITLE
"Back gesture haptic" not workink on latest builds

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Settings#124]
Hello everyone and sorry for my bad english

I use poco x3 nfc
https://github.com/crdroidandroid/android_device_xiaomi_surya

On the latest build, the option "Back gesture haptic" stopped working for me.
The same problem was confirmed by another user on 4pda community.

"Settings => System => Gestures => System navigation => Gesture navigation => Gesture settings (gear) => Back gesture haptic"

It's a minor issue, of course, but having haptics improves the user experience so much that when it works it's taken for granted, and when it doesn't work, you immediately notice it.

P.S.
I'm not sure if this is a general crDroid problem or a device specific one.

**Comment by gwolf2u** [comment]
device specific
test on guacamole and lemonadep as working

**Comment by ghost** [comment]
Hi @gwolf2u 
Thanks for your answer

Since the problem is device specific I'll tag device-tree developer here
@GtrCraft
