### ISSUE TITLE
[Enhancement] Request for Adding cm_strings.xml in Various Languages

### ISSUE THREAD

**Issue by AiraNadih** [crdroidandroid/android_packages_apps_Settings#139]
I've noticed that crDroid already has localization for `strings.xml`, which is great. However, it seems like the `cm_strings.xml` file currently lacks such localization. You can find this file here: [cm_strings.xml](https://github.com/crdroidandroid/android_packages_apps_Settings/blob/14.0/res/values/cm_strings.xml).

I'm suggesting that we expand our localization efforts to include `cm_strings.xml` for various languages. This addition would enhance the user experience for those who prefer using the ROM in their native language and could lead to wider adoption of crDroid.

I am eager to discuss this further and offer my contribution in any way needed.

**Comment by AiraNadih** [comment]
I have created the Simplified Chinese version of the `cm_strings.xml` file for the 14.0 branch and have opened a PR: #140. 

Meanwhile, I noticed that for the 13.0 branch, there is a lack of `cm_strings.xml` files for languages other than Simplified Chinese. I hope that support for these can also be provided on the Crowdin platform.

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android_packages_apps_Settings/pull/140#issuecomment-1883289607
