### ISSUE TITLE
apps from the second user appearing on the first user

### ISSUE THREAD

**Issue by zinhuofc** [crdroidandroid/android_packages_apps_Settings#144]
I've already tested it on crdroid builds on A11, 12.1, 13, and whenever I use multiuser on Android, the applications installed from my second user appear in the list of applications from my first user, with the message "not installed for this user" and also some apps within the app detail the option "uninstall for all users" this is a bad behavior in terms of privacy, especially in authoritarian countries, which in my use, I use the second user to hide my applications from the first, this behavior is fixed and not It is present in most ROMs, especially from A13 onwards, could you fix it in a future release? thanks

![image](https://github.com/crdroidandroid/android_packages_apps_Settings/assets/131195181/566a822f-b5df-472e-b872-2a3f1bb429eb)

**Comment by gwolf2u** [comment]
this is just the way android handles stuff

**Comment by zinhuofc** [comment]
> é assim que o Android lida com as coisas



> this is just the way android handles stuff

and there can be no change? other roms based on crdroid alpha rising do not have this problem

**Comment by zinhuofc** [comment]
> > é assim que o Android lida com as coisas
> 
> > this is just the way android handles stuff
> 
> and there can be no change? other roms based on crdroid alpha droid do not have this problem
