### ISSUE TITLE
 {commit} Show hidden apps on secondary users' app lists 

### ISSUE THREAD

**Issue by zinhuofc** [crdroidandroid/android_packages_apps_Settings#145]
https://github.com/RisingTechOSS/android_frameworks_base/commit/1b0e25a8943c5cfa362b61b11ac0e26831678e93

**Comment by DrFunkenbreakz** [comment]
You know other roms based on crdroid can also fix issues and do a pull request? Crdroid may have the issue, but the responsibility to fix is anyones ehi wants it fixed. If you find the commits to fix this issue, then please do your part and link. Help them to help you 😉
