### ISSUE TITLE
Settings FC on bluetooth toggle 

### ISSUE THREAD

**Issue by gwolf2u** [crdroidandroid/android_packages_apps_Settings#46]
Think this https://github.com/crdroidandroid/android_packages_apps_Settings/commit/b3b3c34817f3b194c727a1caf183d3717018c475 is causing issues on bluetooth toggle 

more info

> 02-27 18:34:45.761 E/AndroidRuntime( 7847): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Switch.setEnabled(boolean)' on a null object reference
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at com.android.settings.bluetooth.BluetoothEnabler.onSwitchToggled(BluetoothEnabler.java:196)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at com.android.settings.widget.MasterSwitchController.onPreferenceChange(MasterSwitchController.java:68)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.support.v7.preference.Preference.callChangeListener(Preference.java:1053)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at com.android.settings.widget.MasterSwitchPreference$1.onClick(MasterSwitchPreference.java:75)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.view.View.performClick(View.java:6294)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.view.View$PerformClick.run(View.java:24770)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.os.Handler.handleCallback(Handler.java:790)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.os.Looper.loop(Looper.java:164)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at android.app.ActivityThread.main(ActivityThread.java:6540)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at java.lang.reflect.Method.invoke(Native Method)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-27 18:34:45.761 E/AndroidRuntime( 7847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by neobuddy89** [comment]
Fixed. 
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/8a1120cbda58dec8d29cd4201e518751086503ba
