### ISSUE TITLE
StorageSettings.java:118.9: COLOR_PRIVATE cannot be resolved to a variable

### ISSUE THREAD

**Issue by Cr-cm** [crdroidandroid/android_packages_apps_Settings#47]
Settings/src/com/android/settings/deviceinfo/StorageSettings.java:118.9: COLOR_PRIVATE cannot be resolved to a variable

**Comment by gwolf2u** [comment]
please provide full log

**Comment by Cr-cm** [comment]
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Builder2'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Closure'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Closure$ValueAndSize'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$ConnectLine'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Future'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$IO'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Input'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptGroup$Node'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsic'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsic3DLUT'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBLAS'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBLAS$Diag'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBLAS$Side'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBLAS$Transpose'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBLAS$Uplo'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBlend'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicBlur'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicColorMatrix'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicConvolve3x3'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicConvolve5x5'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicHistogram'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicLUT'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicResize'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.ScriptIntrinsicYuvToRGB'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Short2'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Short3'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Short4'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Type'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Type$Builder'
Note: the configuration explicitly specifies 'android.renderscript.**' to keep library class 'android.renderscript.Type$CubemapFace'
Note: there were 5 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 2 classes trying to access annotations using reflection.
      You should consider keeping the annotation attributes
      (using '-keepattributes *Annotation*').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 1 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 131 library classes explicitly being kept.
      You don't need to keep library classes; they are already left unchanged.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#libraryclass)
Note: there were 3 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 13 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Preparing output jar [/home/moonlight/cr81/out/target/common/obj/APPS/Snap_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/os/cr81/out/target/common/obj/APPS/Snap_intermediates/classes-desugar.jar]
[ 98% 3515/3568] Building with Jack: /home/os/cr81/out/target/common/obj/APPS/WallpaperCropper_intermediates/with-local/classes.dex
[ 98% 3517/3568] target Package: Snap (/home/os/cr81/out/target/product/shamu/obj/APPS/Snap_intermediates/package.apk)
[ 98% 3522/3568] Building with Jack: /home/os/cr81/out/target/common/obj/APPS/Settings_intermediates/with-local/classes.dex
FAILED: /home/os/cr81/out/target/common/obj/APPS/Settings_intermediates/with-local/classes.dex 
/bin/bash /home/os/cr81/out/target/common/obj/APPS/Settings_intermediates/with-local/classes.dex.rsp
ERROR: /home/os/cr81/packages/apps/Settings/src/com/android/settings/deviceinfo/StorageSettings.java:118.9: COLOR_PRIVATE cannot be resolved to a variable

**Comment by Cr-cm** [comment]
above is full log

**Comment by gwolf2u** [comment]
is it a force sync?
I see this commit that think it fixes it
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/1582ca4a521c1ce25043b092c3df946c6ad9dabd

Edit:
never mind
I see Pranv just pushed it

**Comment by Cr-cm** [comment]
i sync used"repo sync --force-sync -j8" i have a try and build it again

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/1582ca4a521c1ce25043b092c3df946c6ad9dabd

**Comment by Cr-cm** [comment]
fixed
